version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    container_name: backend_container
    depends_on:
      - redis

  interface:
    build:
      context: ./interface
      dockerfile: Dockerfile.prod
    env_file:
      - ./interface/.env
    ports:
      - "5173:5173"
    container_name: interface_container
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6373:6373"

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_pgvector
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
